In [17]:

import pandas as pd

# Load the NASA landslide dataset
nasa_landslide_data = pd.read_csv('nasa_global_landslide_catalog_point.csv')


nasa_landslide_data['event_date'] = pd.to_datetime(nasa_landslide_data['event_date'], errors='coerce')

#Remove all rows with missing values in these essential columns
essential_columns = ['latitude', 'longitude', 'event_date', 'landslide_size']
cleaned_data = nasa_landslide_data.dropna(subset=essential_columns)

###Test for Malaysia data for now, I'll assume the location accuracy is perfect. This is a possible improvement for later.

In [18]:
columns_to_drop = [
    'event_id', 'landslide_setting', 'injury_count', 'storm_name', 'photo_link', 'event_import_source','fatality_count', 'comments', 'country_code','landslide_category',
    'OBJECTID', 'source_name', 'event_title', 'event_description', 
    'location_description', 'Shape', 'source_link', 
    'event_time', 'last_edited_date'
]

cleaned_data = cleaned_data.drop(columns = columns_to_drop, errors = 'ignore')

cleaned_data.head()

,event_date,location_accuracy,landslide_trigger,landslide_size,event_import_id,latitude,longitude,country_name,admin_division_name,gazetteer_closest_point,gazetteer_distance,submitted_date
0,2008-08-01 00:00:00,unknown,rain,large,684,32.5625,107.4500,China,Shaanxi,Micang Shan,19.18,2014-04-01 00:00:00
1,2009-01-02 02:00:00,5km,downpour,small,956,45.4200,-122.6630,United States,Oregon,Portland,2.95,2014-04-01 00:00:00
2,2007-01-19 00:00:00,10km,downpour,large,973,-11.1295,-75.3587,Peru,Junín,San Ramon,2.77,2014-04-01 00:00:00
3,2009-07-31 00:00:00,unknown,monsoon,medium,1067,28.8378,81.7080,Nepal,Bheri,Katti,11.78,2014-04-01 00:00:00
4,2010-10-16 12:00:00,5km,tropical_cyclone,medium,2603,10.3336,123.8978,Philippines,Cebu,Cebu,2.94,2014-04-01 00:00:00

Extract Malaysian data

In [19]:
malaysia_data = cleaned_data[cleaned_data['country_name'] == 'Malaysia']

# Display the first few rows of the filtered dataset
malaysia_data

,event_date,location_accuracy,landslide_trigger,landslide_size,event_import_id,latitude,longitude,country_name,admin_division_name,gazetteer_closest_point,gazetteer_distance,submitted_date
24,2009-01-16 13:00:00,10km,rain,medium,971,1.531000,110.344200,Malaysia,Sarawak,Kuching,5.09,2014-04-01 00:00:00
274,2017-05-25 00:00:00,5km,rain,small,NaN,3.013135,101.770772,Malaysia,Selangor,Kajang,3.57,2017-06-14 18:48:35
328,2017-05-29 02:00:00,5km,unknown,small,NaN,1.543841,110.520859,Malaysia,Sarawak,Semera,16.06,2017-06-16 13:34:15
337,2017-05-18 00:00:00,10km,rain,small,NaN,4.193408,114.042280,Malaysia,Sarawak,Kuala Nyabor,7.54,2017-06-20 20:14:32
352,2016-08-22 06:00:00,1km,downpour,small,NaN,5.395580,100.318010,Malaysia,Pulau Pinang,Georgetown,3.58,2017-06-30 17:45:03.000001
...,...,...,...,...,...,...,...,...,...,...,...,...
14115,2018-11-02 18:45:58,1km,downpour,medium,NaN,5.380758,100.279172,Malaysia,Pulau Pinang,Georgetown,3.98,2020-08-04 18:45:58
14167,2018-10-25 00:06:41,5km,monsoon,unknown,NaN,5.347599,100.251727,Malaysia,Pulau Pinang,Penang International,6.21,2020-07-29 00:06:42.000001
14194,2016-07-01 18:45:58,exact,construction,small,NaN,3.337000,101.529972,Malaysia,Selangor,Selangor,3.58,2020-08-04 18:45:58
14306,2018-09-26 17:30:00,1km,downpour,medium,NaN,3.099315,101.677768,Malaysia,Wilayah Persekutuan Kuala Lumpur,Simpang,3.28,2020-06-16 02:58:44
35652,2022-03-09 00:00:00,1km,continuous_rain,unknown,NaN,3.147890,101.694050,Malaysia,Wilayah Persekutuan Kuala Lumpur,Kuala Lumpur,2.36,2022-04-26 02:09:06

In [22]:
malaysia_data.to_csv('Malaysia_Data.csv', index=False)